# Generated by Django 5.1.4 on 2024-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_4',
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
