# Generated by Django 5.1.4 on 2024-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='sessions', to='quiz.question'),
        ),
    ]
