# Generated by Django 5.1.4 on 2024-12-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizsession_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='QuizSessionAnswer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizsession',
            name='answered_questions',
            field=models.ManyToManyField(through='quiz.QuizSessionAnswer', to='quiz.question'),
        ),
    ]
