# Generated by Django 5.1.4 on 2024-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_answer_quizsessionanswer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsessionanswer',
            old_name='selected_option',
            new_name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='answered_questions',
        ),
        migrations.AlterField(
            model_name='quizsessionanswer',
            name='is_correct',
            field=models.BooleanField(),
        ),
    ]
